# language.py
languages = {
    "en": {
        "configuration_loaded": "Configuration loaded from {config_path}.",
        "error_loading_config": "Error loading configuration: {e}",
        "welcome": "Connected to MQTT broker successfully.",
        "chatbot_error_status": "Chatbot returned error status {status_code}.",
        "start_uploading_file": "Starting upload for file: {file_path}.",
        "error_sftp_upload": "Error uploading file {file_path}: {e}",
        "file_archived": "File {file_path} archived as {archive_name}.",
        "error_archiving_file": "Error archiving file {file_path}: {e}",
        "file_size": "File {file_path} size: {file_size} bytes.",
        "file_limit_reached": "File {file_path} reached size limit of {size_limit} bytes.",
        "new_file_created": "New file created at {file_path}.",
        "cannot_create_new_file": "Cannot create new file of type {file_type} for language {language}.",
        "error_getting_suffixes": "Error getting suffixes: {e}",
        "record_added": "Record added to {file_path}.",
        "invalid_group": "Invalid group type: {groups}.",
        "error_writing_file": "Error writing to file {file_path}: {e}",
        "file_empty_or_corrupted": "File {file_path} is empty or corrupted.",
        "language_sentence_generated": "Language: {language_full} | Sentence: {sentence}",
        "no_translation_file_config": "No translation file configured for language {language}.",
        "no_file_handler_found": "No file handler found for language {language}.",
        "no_translation_file_in_config": "No translation file configured in config for language {language}.",
        "empty_answer_field": "Warning: 'answer' field is empty in the chatbot response.",
        "max_retries_reached": "Maximum retry attempts reached.",
        "communication_error": "Communication error: {e} | Attempt {attempt} of {max_retries}.",
        "waiting_before_retry": "Waiting {wait_seconds} seconds before retrying...",
        "error_in_interpret_and_output": "Error in interpret_and_output: {e}",
        "sending_request_to_chatbot": "Sending request to chatbot (Attempt {attempt}).",
        "chatbot_response": "Chatbot response: {response}",
        "unknown_language": "Unknown language: {language}.",
        "no_sentence_generated": "No sentence generated for language {language_full}.",
        "user_exit": "User initiated exit."
    },
    "de": {
        "configuration_loaded": "Konfiguration geladen von {config_path}.",
        "error_loading_config": "Fehler beim Laden der Konfiguration: {e}",
        "welcome": "Erfolgreich mit dem MQTT-Broker verbunden.",
        "chatbot_error_status": "Chatbot hat Fehlerstatus {status_code} zurückgegeben.",
        "start_uploading_file": "Starte Upload für Datei: {file_path}.",
        "error_sftp_upload": "Fehler beim Hochladen der Datei {file_path}: {e}",
        "file_archived": "Datei {file_path} archiviert als {archive_name}.",
        "error_archiving_file": "Fehler beim Archivieren der Datei {file_path}: {e}",
        "file_size": "Datei {file_path} Größe: {file_size} Bytes.",
        "file_limit_reached": "Datei {file_path} hat das Größenlimit von {size_limit} Bytes erreicht.",
        "new_file_created": "Neue Datei erstellt unter {file_path}.",
        "cannot_create_new_file": "Kann keine neue Datei vom Typ {file_type} für Sprache {language} erstellen.",
        "error_getting_suffixes": "Fehler beim Abrufen der Suffixe: {e}",
        "record_added": "Datensatz hinzugefügt zu {file_path}.",
        "invalid_group": "Ungültiger Gruppentyp: {groups}.",
        "error_writing_file": "Fehler beim Schreiben in die Datei {file_path}: {e}",
        "file_empty_or_corrupted": "Datei {file_path} ist leer oder beschädigt.",
        "language_sentence_generated": "Sprache: {language_full} | Satz: {sentence}",
        "no_translation_file_config": "Keine Übersetzungsdatei für Sprache {language} konfiguriert.",
        "no_file_handler_found": "Kein Dateihandler für Sprache {language} gefunden.",
        "no_translation_file_in_config": "Keine Übersetzungsdatei in der Konfiguration für Sprache {language} konfiguriert.",
        "empty_answer_field": "Warnung: 'answer'-Feld ist in der Chatbot-Antwort leer.",
        "max_retries_reached": "Maximale Anzahl an Wiederholungsversuchen erreicht.",
        "communication_error": "Kommunikationsfehler: {e} | Versuch {attempt} von {max_retries}.",
        "waiting_before_retry": "Warte {wait_seconds} Sekunden bevor erneut versucht wird...",
        "error_in_interpret_and_output": "Fehler in interpret_and_output: {e}",
        "sending_request_to_chatbot": "Sende Anfrage an Chatbot (Versuch {attempt}).",
        "chatbot_response": "Chatbot-Antwort: {response}",
        "unknown_language": "Unbekannte Sprache: {language}.",
        "no_sentence_generated": "Kein Satz für Sprache {language_full} generiert.",
        "user_exit": "Benutzer hat die Anwendung beendet."
    }
}
